# Generated by Django 3.0.1 on 2019-12-24 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockRow',
            fields=[
                ('pk_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hash_id', models.CharField(max_length=100, unique=True)),
                ('version', models.BigIntegerField()),
                ('prev_block', models.CharField(max_length=100)),
                ('merkle_root', models.CharField(max_length=100)),
                ('timestamp', models.BigIntegerField()),
                ('bits', models.CharField(max_length=100)),
                ('nonce', models.CharField(max_length=100)),
                ('txn_count', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('pk_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hash_id', models.CharField(max_length=100)),
                ('version', models.BigIntegerField()),
                ('locktime', models.BigIntegerField()),
                ('segwit', models.BooleanField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.BlockRow')),
            ],
        ),
        migrations.CreateModel(
            name='TxOutput',
            fields=[
                ('pk_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('output_type', models.CharField(max_length=100)),
                ('amount', models.BigIntegerField()),
                ('address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('script_pubkey', models.CharField(max_length=100)),
                ('op_return_data', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='TxInput',
            fields=[
                ('pk_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prev_tx', models.CharField(max_length=100)),
                ('prev_index', models.BigIntegerField()),
                ('script_sig', models.CharField(max_length=100)),
                ('sequence', models.BigIntegerField()),
                ('witness', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.Transaction')),
            ],
        ),
    ]
