# Generated by Django 3.0 on 2019-12-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('prev_block', models.BinaryField()),
                ('merkle_root', models.BinaryField()),
                ('timestamp', models.IntegerField()),
                ('bits', models.BinaryField()),
                ('nonce', models.BinaryField()),
                ('txn_count', models.IntegerField()),
            ],
        ),
    ]
