# Generated by Django 3.0 on 2019-12-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockrow',
            name='bits',
            field=models.BinaryField(editable=True),
        ),
        migrations.AlterField(
            model_name='blockrow',
            name='merkle_root',
            field=models.BinaryField(editable=True),
        ),
        migrations.AlterField(
            model_name='blockrow',
            name='nonce',
            field=models.BinaryField(editable=True),
        ),
        migrations.AlterField(
            model_name='blockrow',
            name='prev_block',
            field=models.BinaryField(editable=True),
        ),
    ]
