# Generated by Django 3.0 on 2019-12-03 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_auto_20191202_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('locktime', models.IntegerField()),
                ('segwit', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='blockrow',
            name='hash_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TxInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_tx', models.BinaryField(editable=True)),
                ('prev_index', models.IntegerField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.Transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.BlockRow'),
        ),
    ]
