# Generated by Django 3.0 on 2019-12-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0004_auto_20191203_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='script_sig',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='sequence',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
