# Generated by Django 3.0 on 2019-12-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0005_auto_20191204_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='script_sig',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sequence',
        ),
        migrations.AddField(
            model_name='txinput',
            name='script_sig',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='txinput',
            name='sequence',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
