# Generated by Django 3.0 on 2019-12-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0006_auto_20191204_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='txinput',
            name='witness',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='txoutput',
            name='op_return_data',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='txoutput',
            name='output_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='txoutput',
            name='script_pubkey',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
