# Generated by Django 3.0 on 2019-12-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0008_auto_20191205_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txinput',
            name='witness',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='txoutput',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='txoutput',
            name='op_return_data',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
