# Generated by Django 3.0 on 2019-12-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0009_auto_20191205_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txinput',
            name='prev_tx',
            field=models.CharField(max_length=100),
        ),
    ]
