# Generated by Django 3.0 on 2019-12-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0011_auto_20191216_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockrow',
            name='bits',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blockrow',
            name='merkle_root',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blockrow',
            name='nonce',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blockrow',
            name='prev_block',
            field=models.CharField(max_length=100),
        ),
    ]
